language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm
matrix:
  include:
    - php: 5.2
      dist: precise
    - php: 5.3
      dist: precise
before_script:
  - composer self-update
  - composer update
script: ./vendor/bin/phpunit
